# 以当前目录为根目录，不再向上查找 .eslintrc
root: true

# 环境定义了预定义的全局变量
env:
  es6: true
  node: true
  mocha: true
  browser: true
  commonjs: true

# parser: typescript-eslint-parser

# JavaScript 语言选项
parserOptions:
  allowImportExportEverywhere: true
  # ECMAScript 版本
  ecmaVersion: 8
  # 设置为 "script" (默认) 或 "module"（如果你的代码是 ECMAScript 模块)。
  sourceType: module
  ecmaFeatures:
    # 启用 JSX
    jsx: true
    # 允许在全局作用域下使用 return 语句
    globalReturn: true
    impliedStrict: true
    experimentalObjectRestSpread: true

# plugins:
#   - typescript
#   - react


# extends:
#   - eslint-config-alloy/typescript

#extends:
#  eslint: recommended
#  plugin: react/recommended

#########################
#  off 或 0 - 关闭规则
#  warn 或 1 - 开启规则，使用警告级别的错误：warn (不会导致程序退出),
#  error 或 2 - 开启规则，使用错误级别的错误：error (当被触发的时候，程序会退出)
#  如果想在代码中取消验证，可以增加/* eslint-disable no-alert, quotes */ 或 // eslint-disable-next-line
#########################
rules:
  # 禁用alert confirm prompt
  no-alert: warn
  # 禁用 Array 构造函数
  no-array-constructor: warn
  # 禁用位运算
  no-bitwise: off
  # 禁用 arguments.caller 或 arguments.callee
  no-caller: warn
  # 禁止catch子句参数与外部作用域变量同名
  no-catch-shadow: error
  # 禁止给类赋值
  no-class-assign: error
  # 禁止在条件表达式中使用赋值语句
  no-cond-assign: error
  # 禁止使用console
  no-console: off
  # 禁止修改const声明的变量
  no-const-assign: error
  # 禁止在条件中使用常量表达式 if(true) if(1)
  no-constant-condition: error
  # 禁止使用continue
  no-continue: off
  # 禁止在正则表达式中使用控制字符
  no-control-regex: error
  # 禁止使用debugger
  no-debugger: error
  # 不能对var声明的变量使用delete操作符
  no-delete-var: error
  # 不能使用看起来像除法的正则表达式/=foo/
  no-div-regex: warn
  # 在创建对象字面量时不允许键重复 {a:1,a:1}
  no-dupe-keys: error
  # 函数参数不能重复
  no-dupe-args: error
  # switch中的case标签不能重复
  no-duplicate-case: error
  # 如果if语句里面有return,后面不能跟else语句
  no-else-return: error
  # 块语句中的内容不能为空
  no-empty: error
  # 正则表达式中的[]内容不能为空
  no-empty-character-class: error
  # 禁止使用空label(import)
  no-empty-label: off
  # 禁止对null使用==或!=运算符
  no-eq-null: error
  # 禁止使用eval
  no-eval: warn
  # 禁止给catch语句中的异常参数赋值
  no-ex-assign: error
  # 禁止扩展native对象
  no-extend-native: error
  # 禁止不必要的函数绑定
  no-extra-bind: error
  # 禁止不必要的bool转换
  no-extra-boolean-cast: error
  # 禁止非必要的括号
  no-extra-parens: warn
  # 禁止多余的冒号
  no-extra-semi: error
  # 禁止switch穿透
  no-fallthrough: warn
  # 禁止省略浮点数中的0 .5 3.
  no-floating-decimal: error
  # 禁止重复的函数声明
  no-func-assign: error
  # 禁止隐式转换
  no-implicit-coercion: warn
  # 禁止使用隐式eval
  no-implied-eval: error
  # 禁止行内注释
  no-inline-comments: off
  # 禁止在块语句中使用声明(变量或函数)
  no-inner-declarations:
    - error
    - functions
  # 禁止无效的正则表达式
  no-invalid-regexp: error
  # 禁止无效的this，只能用在构造器，类，对象字面量
  no-invalid-this: warn
  # 不能有不规则的空格
  no-irregular-whitespace: error
  # 禁止使用__iterator__ 属性
  no-iterator: error
  # label名不能与var声明的变量名相同
  no-label-var: error
  # 禁止标签声明
  no-labels: error
  # 禁止不必要的嵌套块
  no-lone-blocks: error
  # 禁止else语句内只有if语句
  no-lonely-if: error
  # 禁止在循环中使用函数（如果没有引用外部变量不形成闭包就可以）
  no-loop-func: warn
  # 声明时不能混用声明类型
  no-mixed-requires:
    - off
    - false
  # 禁止混用tab和空格
  no-mixed-spaces-and-tabs:
    - error
    - false
  # 换行风格 '\n' unix(for LF) and '\r\n' for windows(CRLF)，默认unix
  linebreak-style:
    - warn
    - unix
  # 不能用多余的空格
  no-multi-spaces: warn
  # 字符串不能用\换行
  no-multi-str: error
  # 空行最多不能超过3行
  no-multiple-empty-lines:
    - warn
    - max: 3
  # 不能重写native对象
  no-native-reassign: error
  # in 操作符的左边不能有!
  no-negated-in-lhs: error
  # 禁止使用嵌套的三目运算
  no-nested-ternary: off
  # 禁止在使用new构造一个实例后不赋值
  no-new: warn
  # 禁止使用new Function
  no-new-func: warn
  # 禁止使用new Object()
  no-new-object: error
  # 禁止使用new require
  no-new-require: error
  # 禁止使用new创建包装实例，new String new Boolean new Number
  no-new-wrappers: error
  # 不能调用内置的全局对象，比如Math() JSON()
  no-obj-calls: off
  # 禁止使用八进制数字
  no-octal: warn
  # 禁止使用八进制转义序列
  no-octal-escape: warn
  # 禁止给参数重新赋值
  no-param-reassign: warn
  # node中不能使用__dirname或__filename做路径拼接
  no-path-concat: off
  # 禁止使用++，--
  no-plusplus: off
  # 禁止使用process.env
  no-process-env: off
  # 禁止使用process.exit()
  no-process-exit: off
  # 禁止使用__proto__属性
  no-proto: error
  # 禁止重复声明变量
  no-redeclare: error
  # 禁止在正则表达式字面量中使用多个空格 /foo bar/
  no-regex-spaces: error
  # 如果禁用了指定模块，使用就会报错
  no-restricted-modules: off
  # return 语句中不能有赋值表达式
  no-return-assign: off
  # 禁止使用javascript:void(0)
  no-script-url: off
  # 不能比较自身
  no-self-compare: error
  # 禁止使用逗号运算符
  no-sequences: off
  # 外部作用域中的变量不能与它所包含的作用域中的变量或参数同名
  no-shadow: error
  # 严格模式中规定的限制标识符不能作为声明时的变量名使用
  no-shadow-restricted-names: error
  # 函数调用时 函数名与()之间不能有空格
  no-spaced-func: error
  # 禁止稀疏数组 [1,,2]
  no-sparse-arrays: error
  # nodejs 禁止同步方法
  no-sync: off
  # 禁止使用三目运算符
  no-ternary: off
  # 禁止多余空格 每行结束后
  no-trailing-spaces: warn
  # 在调用super()之前不能使用this或super
  no-this-before-super: off
  # 禁止抛出字面量错误 throw "error";
  no-throw-literal: error
  # 禁止使用模版字符串
  no-template-curly-in-string: error
  # 不能有未定义的变量
  no-undef: warn
  # 变量初始化时不能直接给它赋值为undefined
  no-undef-init: error
  # 不能使用undefined
  no-undefined: warn
  # 避免多行表达式
  no-unexpected-multiline: error
  # 标识符不能以_开头或结尾
  no-underscore-dangle: off
  # 禁止不必要的嵌套 var isYes = answer === 1 ? true : false;
  no-unneeded-ternary: error
  # 不能有无法执行的代码
  no-unreachable: error
  # 禁止无用的表达式
  no-unused-expressions: warn
  # 不能有声明后未被使用的变量或参数
  no-unused-vars: warn
  # 未定义前不能使用
  no-use-before-define: warn
  # 禁止不必要的call和apply
  no-useless-call: warn
  # 禁用void操作符
  no-void: error
  # 禁用var，用let和const代替
  no-var: off
  # 不能有警告备注
  no-warning-comments: off
  # 禁用with
  no-with: error
  # 是否允许非空数组里面有多余的空格
  array-bracket-spacing:
    - error
    - never
  # 箭头函数用小括号括起来
  arrow-parens:
    - warn
    - as-needed
  # =>的前/后括号
  arrow-spacing: off
  # 在对象中使用getter/setter
  accessor-pairs: off
  # 块语句中使用var
  block-scoped-var: off
  # 大括号风格
  brace-style:
    - warn
    - 1tbs
  # 避免多次调用回调什么的
  callback-return: warn
  # 强制驼峰法命名
  camelcase: error
  # 对象字面量项尾不能有逗号
  comma-dangle:
    - error
    - only-multiline
  # 逗号前后的空格
  comma-spacing: off
  # 逗号风格，换行时在行首还是行尾
  comma-style:
    - error
    - last
  # 循环复杂度 [0, 11]
  complexity: off
  # 是否允许计算后的键名什么的
  computed-property-spacing:
    - off
    - never
  # return 后面是否允许省略
  consistent-return: off
  # this别名
  consistent-this:
    - error
    - that
  # 非派生类不能调用super，派生类必须调用super
  constructor-super: off
  # 必须使用 if(){} 中的{}
  curly:
    - error
    - all
  # switch语句最后必须有default
  default-case: off
  # 对象访问符的位置，换行的时候在行首还是行尾
  dot-location: off
  # 避免不必要的方括号
  dot-notation:
    - off
    - allowKeywords: true
  # 文件以单一的换行符结束
  eol-last: off
  # 必须使用全等
  eqeqeq:
    - error
    - allow-null
  # 函数表达式必须有名字
  func-names: off
  func-style:
    - off
    - declaration
  # 生成器函数*的前后空格
  generator-star-spacing: off
  # for in循环要用if语句过滤
  guard-for-in: off
  # nodejs 处理错误
  handle-callback-err: off
  # 变量名长度
  id-length:
    - off
    - min: 3
  # 缩进风格
  indent:
    - warn
    - 2
    - SwitchCase: 1
  # 声明时必须赋初值
  init-declarations: off
  # 对象字面量中冒号的前后空格
  key-spacing:
    - off
    - align: colon
      beforeColon: false
      afterColon: true
  # 行前/行后备注
  lines-around-comment: off
  # 嵌套块深度
  max-depth:
    - warn
    - 8
  # 禁止单行超出220字节
  max-len:
    - off
    - 220
  # 回调嵌套深度
  max-nested-callbacks:
    - off
    - 2
  # 函数最多只能有3个参数
  max-params:
    - off
    - 3
  # 函数内最多有几个声明
  max-statements:
    - off
    - 10
  # 函数名首行大写必须使用new方式调用，首行小写必须用不带new方式调用
  new-cap: error
  # new时必须加小括号
  new-parens: error
  # 变量声明后是否需要空一行
  newline-after-var: off
  # 大括号内是否允许不必要的空格
  object-curly-spacing:
    - off
    - never
  # 强制对象字面量缩写语法
  object-shorthand: off
  # 连续声明
  one-var: off
  # 赋值运算符 += -=什么的
  operator-assignment:
    - off
    - always
  # 换行时运算符在行尾还是行首
  operator-linebreak:
    - error
    - after
  # 块语句内行首行尾是否要空行
  padded-blocks: off
  # 首选const
  prefer-const: off
  # 首选展开运算
  prefer-spread: off
  # 首选Reflect的方法
  prefer-reflect: off
  # 引号类型 `` "" ''
  quotes:
    - error
    - single
  # 对象字面量中的属性名是否强制双引号
  quote-props:
    - error
    - always
  # parseInt必须指定第二个参数
  radix: off
  # 命名检测
  id-match: off
  # 生成器函数必须有yield
  require-yield: off
  # 语句强制分号结尾
  semi:
    - error
    - always
  # 分号前后空格
  semi-spacing:
    - off
    - before: false
      after: false
  # 变量声明时排序
  sort-vars: off
  # 关键字后面是否要空一格
  space-after-keywords:
    - off
    - always
  # 不以新行开始的块{前面要不要有空格
  space-before-blocks:
    - off
    - always
  # 函数定义时括号前面要不要有空格
  space-before-function-paren:
    - off
    - always
  # 小括号里面要不要有空格
  space-in-parens:
    - off
    - never
  # 中缀操作符周围要不要有空格
  space-infix-ops: off
  # return throw case后面要不要加空格
  space-return-throw-case: off
  # 一元运算符的前/后要不要加空格
  space-unary-ops:
    - off
    - words: true
      nonwords: false
  # 注释风格要不要有空格什么的
  spaced-comment: off
  # 使用严格模式
  strict: off
  # 禁止比较时使用NaN，只能用isNaN()
  use-isnan: error
  # jsdoc规则
  valid-jsdoc: off
  # 必须使用合法的typeof的值
  valid-typeof: error
  # var必须放在作用域顶部
  vars-on-top: off
  wrap-iife:
    - error
    - inside
  # 正则表达式字面量用小括号包起来
  wrap-regex: off
  # 禁止尤达条件 if("blue" == theSky){...}
  yoda:
    - error
    - never
  import/no-unresolved: off
  global-require: off

  # 类和接口的命名必须遵守帕斯卡命名法，比如 PersianCat
  # typescript/class-name-casing: error

globals:
  module: false
  window: false
  document: false
  avalon: true
  localStorage: true
